export const WEB_PET_CONFIG = {
  poseBasePath: "/web-pet/robot/poses",
  expressionBasePath: "/web-pet/robot/expressions",
  desktopSize: 120,
  mobileSize: 88,
  mobileBreakpoint: 650,
  viewportPadding: 8,
  rightDockGap: 58,
  bottomDockGap: 18,
  firstActionDelayMs: 10_000,
  actionDelayMinMs: 18_000,
  actionDelayMaxMs: 42_000,
  expressionFirstDelayMs: 260,
  frameTransitionMs: 160,
  positionStorageKey: "blinga:web-pet-position:v1",
} as const;
