export const WEB_PET_CONFIG = {
  poseBasePath: "/web-pet/robot/poses",
  expressionBasePath: "/web-pet/robot/expressions",
  desktopSize: 120,
  mobileSize: 88,
  mobileBreakpoint: 650,
  viewportPadding: 8,
  rightDockGap: 58,
  bottomDockGap: 18,
  firstActionDelayMs: 20_000,
  actionDelayMinMs: 20_000,
  actionDelayMaxMs: 20_000,
  expressionFirstDelayMs: 1_800,
  frameTransitionMs: 160,
  positionStorageKey: "blinga:web-pet-position:v1",
} as const;
